- gistID: 'ec35fdd1bb2fb6a06fb0ec0bf22653a8'
  files:
  - 'hello.txt': 
      content: "Hello World"
    README.md:
      content: "# README"
- gistID: '456'
  files:
  - 'bye.txt':
      content: "Goodbye"
- gistID: 'ec35fdd1bb2fb6a06fb0ec0bf22653a8'
  files:
  - 'YOLO.ts':
      content: "console.log(\"YOLO\")"
    YOLO.go:
      content: "package main\n\nfunc main() {}"