- gistID: 'ec35fdd1bb2fb6a06fb0ec0bf22653a8'
  files:
    'hello.txt': 
      contents: "Hello World"
    README.md:
      contents: "# README"

- gistID: '456'
    files:
    'bye.txt':
      contents: "Goodbye"

- gistID: 'ec35fdd1bb2fb6a06fb0ec0bf22653a8'
    files:
    'YOLO.ts':
      contents: "console.log(\"YOLO\")"
    YOLO.go:
      contents: "package main\n\nfunc main() {}"