# ===========
# GIST-MIRROR
# ===========

name: Gist-Mirror
description: Mirror files from your repository to GitHub Gists
author: Shresht7

runs:
  using: node16
  main: dist/index.js

branding:
  icon: code
  color: white

# Inputs
# ======

inputs:
  gists:
    description: YAML mapping GistIDs to their corresponding files
    required: true

  dryrun:
    description: No actual changes will be made if dryrun is enabled
    default: "true"
    required: false
