# ===========
# GIST-MIRROR
# ===========

name: Gist-Mirror
description: Mirror files from your repository to GitHub Gists
author: Shresht7

runs:
  using: node16
  main: dist/index.js

branding:
  icon: code
  color: white

# Inputs
# ======

inputs:
  # Dry-run toggle
  # --------------

  dryrun:
    description: "Dry-run toggle. Gist-Mirror will not make any actual changes if true (default: `true`)"
    default: "true"
    required: false

  # File-Gist map
  # -------------

  gists:
    description: "File containing the array of GistID and corresponding files"
    default: "gists.yml"
    required: true
