# ===========
# GIST-MIRROR
# ===========

name: 'Gist-Mirror'
description: 'Mirror files from your repo to gists'
author: 'Shresht7'

branding:
  icon: code
  color: white

# Inputs
# ======

inputs:

  # Dry-run toggle
  # --------------

  dryrun:
    description: 'Dry-run toggle. Gist-Mirror will not make any actual changes if true (default: true)'
    default: true

  # File-Gist map
  # -------------

  gists:
    description: 'File containing the array of GistID and corresponding files'
    default: 'gists.yml'

# Runs
# ====

runs:
  using: 'node16'
  main: 'dist/index.js'