# ========
# VALIDATE
# ========

name: Validate

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # Build
  # -----

  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm run build

  # Dist
  # ----

  check-dist: # Check whether the checked-in dist actually matches what we expect it to be
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm run build

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If dist/index.js was different than expected, create a pull request
      - name: Create pull request
        id: create-pull-request
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        uses: peter-evans/create-pull-request@v3
        with:
          title: Build 📦
          commit-message: Build 📦
          branch: build
          delete-branch: true
          # labels: |
          #   automated
          assignees: Shresht7
          token: ${{ secrets.GITHUB_TOKEN }}

  # Test
  # ----

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: test
        uses: ./
        with:
          dry-run: true
          gists: |
            - id: bed31c34989a8ee63ec0dc4981a74c9a
              description: Gist-Mirror Action
              files:
                - README.md
                - .github/workflows/gist-mirror.yml
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
